import type { NextPage } from "next";
import Head from "next/head";
import DownloadSection from "../components/DownloadSection";

const DownloadToExcel: NextPage = () => {
  // get data from api

  return (
    <>
      <Head>
        <title>The Gowdie - Download to Excel</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DownloadSection />
    </>
  );
};

export default DownloadToExcel;
