import type { NextPage } from "next";
import Head from "next/head";
import GBLUSection from "../components/GBLUSection";
import Sidebar from "../components/Sidebar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>The Gowdie</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GBLUSection />
      {/* <Sidebar /> */}
    </>
  );
};

export default Home;
